CREATE DATABASE IF NOT EXISTS beauty_makeup_shop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE beauty_makeup_shop;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS order_items; DROP TABLE IF EXISTS orders; DROP TABLE IF EXISTS products; DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(160) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,role ENUM('admin','customer') DEFAULT 'customer',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE products (id INT AUTO_INCREMENT PRIMARY KEY,product_code VARCHAR(50) NULL,name VARCHAR(255) NOT NULL,brand VARCHAR(120) NOT NULL,category VARCHAR(100) NOT NULL,price INT NOT NULL,stock INT NOT NULL DEFAULT 10,image VARCHAR(255) NOT NULL,description TEXT NOT NULL,benefit TEXT NOT NULL,ingredients TEXT NOT NULL,usage_text TEXT NOT NULL,status TINYINT(1) DEFAULT 1,sort_order INT DEFAULT 99,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE orders (id INT AUTO_INCREMENT PRIMARY KEY,customer_name VARCHAR(160) NOT NULL,phone VARCHAR(20) NOT NULL,address TEXT NOT NULL,note TEXT NULL,total INT NOT NULL DEFAULT 0,status VARCHAR(50) NOT NULL DEFAULT 'Chờ xác nhận',payment_status VARCHAR(50) NOT NULL DEFAULT 'Chưa thanh toán',payment_code VARCHAR(80) NULL,created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE order_items (id INT AUTO_INCREMENT PRIMARY KEY,order_id INT NOT NULL,product_id INT NOT NULL,product_code VARCHAR(50) NULL,product_name VARCHAR(255) NOT NULL,price INT NOT NULL,quantity INT NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO users(name,email,password,role) VALUES ('Quản trị viên','admin@gmail.com','$2y$12$osim3.pR9yKQReEenQmV/.LCinnNcGLmNPxpSGpnixN7e2azPkaOu','admin');
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('GlowBeauty 4 Colors Eyeshadow','GlowBeauty','Phấn mắt',349000,10,'5d9f1105-752c-4481-97f4-6f676c7c684e.png','Bảng phấn mắt 4 ô tông hồng đào, ánh nhũ nhẹ và chất phấn mịn, phù hợp trang điểm hằng ngày hoặc dự tiệc.','Giúp đôi mắt sáng hơn, dễ phối màu, lên màu chuẩn và tạo hiệu ứng mắt có chiều sâu.','4 tông màu gồm lì, nhũ mịn, nhũ ánh kim và nhũ glitter; hạt phấn mịn, dễ tán.','Dùng cọ lấy lượng phấn vừa đủ, tán từ màu nhạt đến màu đậm ở bầu mắt và đuôi mắt.',1,1);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('GlowBeauty Soft Rose Blush','GlowBeauty','Phấn má',259000,10,'186f6edf-cd4a-4993-ae3b-fd382410e02a.png','Phấn má GlowBeauty tông hồng tự nhiên, thiết kế nữ tính, giúp gương mặt tươi tắn và mềm mại.','Tạo má hồng rạng rỡ, làm khuôn mặt có sức sống, phù hợp makeup tự nhiên.','Bột phấn mịn, sắc hồng đào dễ dùng, độ bám ổn định.','Dùng cọ tán nhẹ lên gò má, có thể chồng nhiều lớp để tăng sắc độ.',1,2);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('GlowBeauty Radiant Foundation','GlowBeauty','Kem nền',389000,10,'7e22a2c4-47cb-40f1-9bea-ddcc3af173c6.png','Kem nền GlowBeauty tạo lớp nền mỏng nhẹ, sáng mịn, phù hợp phong cách makeup cao cấp.','Che phủ nhẹ đến vừa, giúp da đều màu, mịn hơn và giữ nền tự nhiên.','Kết cấu lỏng mịn, có độ ẩm, phù hợp trang điểm hằng ngày.','Lấy 1-2 pump, tán đều bằng mút hoặc cọ từ giữa mặt ra ngoài.',1,3);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('GlowBeauty Soft Veil Loose Powder','GlowBeauty','Phấn phủ',299000,10,'b999eddd-f76a-4dc3-82a7-a5ea08c5e78e.png','Phấn phủ GlowBeauty giúp cố định lớp nền, tạo hiệu ứng mịn lì nhưng không làm mặt bị dày.','Kiềm dầu nhẹ, giảm bóng nhờn, giúp lớp nền bền và mịn hơn.','Hạt phấn siêu mịn, finish tự nhiên, phù hợp nhiều tông da.','Dặm nhẹ vùng chữ T, dưới mắt và vùng dễ đổ dầu sau bước kem nền.',1,4);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('GlowBeauty Glow Velvet Lipstick','GlowBeauty','Son môi',279000,10,'e3994ca6-7672-4e2d-9dc0-63a1c99cfbbb.png','Son GlowBeauty tông đỏ hồng nữ tính, chất son mịn, lên màu rõ và phù hợp nhiều phong cách.','Giúp môi nổi bật, làm sáng khuôn mặt, phù hợp đi học, đi làm và dự tiệc.','Kết cấu velvet mềm, sắc tố rõ, hạn chế khô môi khi dùng đúng cách.','Thoa trực tiếp lên môi hoặc tán lòng môi để tạo hiệu ứng nhẹ nhàng.',1,5);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('GlowBeauty Rose Hydrating Toner','GlowBeauty','Toner & Essence',259000,10,'d766a7f3-1211-40d7-b144-7c50b8323349.png','Toner hoa hồng GlowBeauty hỗ trợ cân bằng da sau rửa mặt và chuẩn bị da cho các bước dưỡng tiếp theo.','Cấp ẩm nhẹ, làm dịu da, giúp da mềm và dễ hấp thu serum hơn.','Chiết xuất hoa hồng, thành phần cấp ẩm, kết cấu nước nhẹ.','Đổ ra bông tẩy trang hoặc lòng bàn tay, vỗ nhẹ sau bước làm sạch.',1,6);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('GlowBeauty Premium Combo 7 sản phẩm','GlowBeauty','Combo',1499000,10,'80c93bee-84bb-4c67-8b4d-c1672ef08fcd.png','Combo chăm sóc và trang điểm toàn diện gồm sữa rửa mặt, toner, serum, kem dưỡng, cushion, son và bảng mắt.','Tiết kiệm chi phí, đầy đủ sản phẩm cơ bản cho routine làm đẹp hằng ngày.','Bộ sản phẩm được phối theo tông hồng rose-gold, phù hợp làm quà tặng.','Dùng theo thứ tự: làm sạch, cân bằng, serum, kem dưỡng, nền, mắt và son.',1,7);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('GlowBeauty Luxury Makeup Banner Collection','GlowBeauty','Combo',2350000,10,'3d7437b9-c6c3-4326-a9df-ca2ee66a36d6.png','Bộ sưu tập makeup cao cấp của GlowBeauty gồm sản phẩm nền, son, phấn mắt và phấn má tông rose-gold.','Mang lại phong cách trang điểm sang trọng, đồng bộ và nổi bật.','Các sản phẩm trong bộ có tông màu dễ dùng, phù hợp nhiều dịp.','Sử dụng từng sản phẩm theo nhu cầu trang điểm cá nhân.',1,8);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Biore Sạch Dịu Nhẹ Sáng Mịn & Dưỡng Ẩm','Biore','Sữa rửa mặt',89000,10,'0001.jpg','Sữa rửa mặt Biore giúp làm sạch da nhẹ nhàng, phù hợp sử dụng hằng ngày.','Làm sạch bụi bẩn, dầu thừa, hỗ trợ da sáng mịn và mềm hơn sau khi rửa.','Chiết xuất nước vo gạo, công nghệ thanh lọc da, kết cấu tạo bọt nhẹ.','Làm ướt mặt, lấy lượng vừa đủ tạo bọt, massage 30-60 giây rồi rửa sạch.',1,9);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Simple Refreshing Facial Wash','Simple','Sữa rửa mặt',125000,10,'rua_mat_simple-3.jpg','Sữa rửa mặt Simple nổi bật với công thức dịu nhẹ, phù hợp da nhạy cảm.','Làm sạch da mà không gây cảm giác khô căng, giúp da thông thoáng.','Không hương liệu, không màu nhân tạo, công thức lành tính.','Dùng sáng và tối, massage nhẹ trên da ẩm rồi rửa sạch.',1,10);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('CeraVe Foaming Facial Cleanser','CeraVe','Sữa rửa mặt',365000,10,'SRM-Cerave-Foaming-Facial-For-Normal-To-Oily-Skin-.jpeg','Sữa rửa mặt tạo bọt CeraVe dành cho da thường đến da dầu.','Làm sạch dầu thừa, hỗ trợ bảo vệ hàng rào ẩm tự nhiên của da.','Ceramides, Niacinamide và Hyaluronic Acid.','Dùng 1-2 lần/ngày, tránh vùng mắt và rửa lại bằng nước sạch.',1,11);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Cetaphil Gentle Skin Cleanser','Cetaphil','Sữa rửa mặt',345000,10,'sua-rua-mat-diu-nhe-cetaphil-gentle-skin-cleanser-473ml-070323-050017-600x600.jpg','Sữa rửa mặt Cetaphil Gentle Skin Cleanser phù hợp da khô, da nhạy cảm và dùng hằng ngày.','Làm sạch dịu nhẹ, hỗ trợ duy trì độ ẩm và giảm cảm giác căng da.','Công thức dịu nhẹ, không xà phòng mạnh, phù hợp nhiều loại da.','Massage trên da ẩm, rửa sạch hoặc lau bằng bông mềm tùy nhu cầu.',1,12);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Proactiv Revitalizing Toner','Proactiv','Toner & Essence',320000,10,'61545kOb3bL._SL1500_.jpg','Toner Proactiv hỗ trợ chăm sóc da dầu mụn, giúp da thông thoáng hơn sau bước rửa mặt.','Hỗ trợ cân bằng da, làm sạch cặn thừa và tạo cảm giác tươi mát.','Công thức toner dành cho da dễ nổi mụn.','Dùng bông tẩy trang lau nhẹ sau khi rửa mặt, tránh vùng mắt.',1,13);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Su:m37 Skin Saver Essential Cleansing Foam','Su:m37','Sữa rửa mặt',260000,10,'62575e2ebc921ca7dd4b49efd9e67e01.jpg','Sữa rửa mặt Su:m37 Skin Saver tạo bọt mịn, phù hợp làm sạch dịu nhẹ.','Loại bỏ bụi bẩn, giúp da mềm và sạch thoáng sau khi dùng.','Công thức bọt mịn, cảm giác dịu trên da.','Tạo bọt với nước, massage nhẹ rồi rửa sạch.',1,14);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Quiym Aqua Vitalize Skincare Set','Quiym','Skincare',499000,10,'a97d766d-62a5-420b-b225-68e695629534.__CR0-0-970-600_PT0_SX970_V1___.jpg','Bộ chăm sóc da cấp nước gồm serum, toner, kem dưỡng và sữa rửa mặt tông xanh aqua.','Cấp ẩm, hỗ trợ da căng mướt, phù hợp da thiếu nước.','Hyaluronic Acid, chiết xuất biển và thành phần cấp ẩm.','Dùng theo routine: rửa mặt, toner, serum, kem dưỡng.',1,15);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('CNP Laboratory Propolis Treatment Essence','CNP Laboratory','Toner & Essence',420000,10,'vn-11134207-7ras8-m2vwo5c0s3ra9e.jfif','Tinh chất CNP Propolis Treatment Ampule Essence hỗ trợ làm dịu và phục hồi da.','Giúp da mềm, sáng khỏe và có độ bóng tự nhiên.','Chiết xuất keo ong, thành phần cấp ẩm và làm dịu.','Dùng sau toner, vỗ nhẹ đến khi thấm.',1,16);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Rare Beauty Soft Pinch Tinted Lip Oil','Rare Beauty','Son môi',395000,10,'son-duong-rare-beauty-soft-pinch-tinted-lip-oil-mau-hong-kho-2-jpg-1680486361-03042023084601.webp','Son dầu Rare Beauty tạo sắc môi hồng nhẹ, bóng khỏe và mềm mại.','Dưỡng môi, tạo màu tự nhiên, phù hợp makeup nhẹ.','Kết cấu lip oil mỏng nhẹ, sắc hồng khô dễ dùng.','Thoa trực tiếp lên môi, dặm lại khi cần.',1,17);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Merzy The Watery Dew Tint V6 Siren','Merzy','Son môi',179000,10,'f7973ec129c17238ddfc48d109b88448.png','Son tint Merzy V6 Siren màu đỏ nổi bật, hiệu ứng môi căng mọng.','Lên màu rõ, tạo hiệu ứng full môi hoặc lòng môi quyến rũ.','Chất tint bóng nhẹ, màu đỏ cam dễ nổi bật.','Thoa một lớp mỏng và tán đều, có thể chồng lớp để đậm hơn.',1,18);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Merzy New Watery Dew Tint WD21','Merzy','Son môi',169000,10,'website_nd-10_db148e2cda6c4858af668121aebc5230_master.png','Son Merzy WD21 tông đỏ hồng khô, chất tint nước bóng nhẹ.','Tạo môi tươi tắn, mọng nhẹ, phù hợp đi học đi làm.','Kết cấu watery tint, sắc đỏ hồng dễ dùng.','Thoa lòng môi hoặc full môi tùy phong cách.',1,19);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Glamrr Q Long Wear Lip Cream','Glamrr Q','Son môi',199000,10,'bang-mau-son-glamrr-q-moi-nhat-glamrr-q-long-wear-lip-cream-1-fa5f7a0e.jpg','Son kem Glamrr Q Long Wear Lip Cream có độ bám màu tốt và finish hiện đại.','Lên màu đậm, giúp môi sắc nét, phù hợp makeup cá tính.','Chất son kem lì, công thức bền màu.','Gạt bớt son trên cọ, thoa từ lòng môi ra viền môi.',1,20);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Romand Better Than Cheek Blush','Romand','Phấn má',235000,10,'18w401_-_2024-01-17t163224.025_279a2f7231824c3cbcb25e25009bf52d_large.png','Phấn má Romand tông tự nhiên, chất phấn mịn dễ tán.','Tạo hiệu ứng má hồng nhẹ nhàng, giúp gương mặt tươi sáng.','Bột phấn mịn, tông màu nude hồng dễ phối.','Dùng cọ lấy phấn, tán nhẹ lên vùng gò má.',1,21);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('YSL Make Me Blush Bold Blurring Blush','YSL','Phấn má',950000,10,'phan-ma-hong-yves-saint-laurent-ysl-make-me-blush-bold-blurring-blush-87-pink-voltage-mau-hong-dao-6g-68e389735f282-06102025161843.webp','Phấn má YSL tông hồng đào cao cấp, thiết kế sang trọng.','Tạo hiệu ứng ửng hồng nổi bật, làm mềm đường nét khuôn mặt.','Chất phấn mịn, màu hồng đào dễ nổi bật.','Tán nhẹ từng lớp để đạt độ hồng mong muốn.',1,22);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Dasique Blending Mood Cheek Palette','Dasique','Phấn má',315000,10,'vn-11134207-7r98o-lw1fkikj774pc0.jfif','Bảng phấn má Dasique 4 màu tông hồng dễ thương, phù hợp makeup Hàn Quốc.','Tạo má hồng nhiều sắc độ, dễ phối màu theo phong cách.','4 ô màu hồng đào, hồng sữa và hồng tươi.','Dùng riêng từng màu hoặc phối các ô để tạo màu má hài hòa.',1,23);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('3CE Face Blush Nude Peach','3CE','Phấn má',295000,10,'phan-ma-hong-3ce-face-blush-5g-nude-peach_2c394fba64e14cb7b11074ede798e806_large.jpg','Phấn má 3CE màu nude peach cho hiệu ứng má tự nhiên.','Giúp khuôn mặt tươi hơn mà vẫn giữ phong cách nhẹ nhàng.','Phấn nén mịn, tông nude đào dễ dùng.','Tán lên gò má bằng cọ mềm.',1,24);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Veecci 4 ô Blush & Highlight','Veecci','Phấn mắt',189000,10,'bang_phan_ma___highlight_4_o_veecci__4__608fc3d99ce44793a75e3ddd53f74fc0.jpg','Bảng Veecci 4 ô kết hợp phấn má và highlight tông hồng đào.','Tạo điểm nhấn bắt sáng, làm gương mặt rạng rỡ hơn.','Gồm màu lì, nhũ nhẹ và highlight.','Dùng cọ nhỏ tán lên mắt, má hoặc vùng cần bắt sáng.',1,25);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Makeup By Mario SurrealSkin Foundation','Makeup By Mario','Kem nền',620000,10,'vn-11134207-7r98o-luvji4fa7imq9b.jfif','Kem nền Makeup By Mario cho lớp nền mỏng mịn, phù hợp phong cách da tự nhiên.','Giúp da đều màu, tạo hiệu ứng mềm mịn và dễ chồng lớp ở vùng cần che phủ.','Kết cấu liquid foundation, finish tự nhiên, dễ tán.','Lắc đều, lấy lượng nhỏ và tán từ trung tâm gương mặt ra ngoài.',1,26);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Make Up For Ever HD Skin Foundation','Make Up For Ever','Kem nền',890000,10,'vn-11134207-7ras8-mc08sotjs22a9d.jfif','Kem nền HD Skin tạo lớp nền chuyên nghiệp, phù hợp chụp ảnh và makeup lâu giờ.','Che phủ ổn, giữ nền mịn và tự nhiên trên da.','Kết cấu liquid foundation, nhiều tông màu.','Tán đều bằng bông mút ẩm hoặc cọ nền.',1,27);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Maybelline Super Stay Lumi Matte Foundation','Maybelline','Kem nền',298000,10,'kem-nen-maybelline-super-stay-up-to-30h-lumi-matte-foundation-spf16-pa35ml-5.jpg','Kem nền Maybelline Super Stay Lumi Matte hỗ trợ nền lâu trôi và sáng mịn.','Giúp da đều màu, che phủ khuyết điểm nhẹ đến vừa.','Kết cấu nền mỏng nhẹ, SPF16 PA+++.','Lắc đều trước khi dùng, tán từng lớp mỏng.',1,28);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Carslan Lasting Moisture Foundation','Carslan','Kem nền',250000,10,'kem_nen_carslan_lasting_moisture_foundation__5__776a71f9d377405c85df5d4e7861343e.jpg','Kem nền Carslan Lasting Moisture tạo lớp nền ẩm mịn, phù hợp makeup tự nhiên.','Che phủ nhẹ, hỗ trợ da căng bóng và đều màu.','Kết cấu dưỡng ẩm, finish tự nhiên.','Tán đều sau bước dưỡng và kem lót.',1,29);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('ColorKey Airy Longwear Foundation','ColorKey','Kem nền',269000,10,'combo-colorkey-kem-nen-w2-30g-xit-co-dinh-lop-trang-diem-nam-cham-den-100ml-2-1708597625_img_800x800_eb97c5_fit_center.jpg','Kem nền ColorKey Airy Longwear có lớp nền thoáng khí, mềm mại và lâu trôi.','Tạo nền mỏng nhẹ, hỗ trợ đều màu và bền lớp trang điểm.','Kết cấu lỏng nhẹ, độ cấp ẩm ổn, phù hợp da hỗn hợp.','Lấy lượng nhỏ, tán đều và chồng lớp ở vùng cần che phủ.',1,30);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('3CE Stylenanda Waterful Foundation','3CE','Kem nền',420000,10,'figure-1651051253314.png','Kem nền 3CE Waterful Foundation tạo lớp nền mềm mịn và hiệu ứng da trong trẻo.','Che khuyết điểm nhẹ, cải thiện vẻ ngoài nền da và nếp nhăn nhỏ.','Kết cấu waterful foundation, finish mỏng nhẹ.','Tán bằng mút ẩm để lớp nền tự nhiên hơn.',1,31);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('NARS Radiant Creamy Concealer','NARS','Che khuyết điểm',720000,10,'z4985812587158_338a830ffecc2773109521584ea295a8_8c6fcb18c4a84156a620a335763f49af_master.jpg','Che khuyết điểm NARS nổi tiếng với độ che phủ tốt và finish tự nhiên.','Che quầng thâm, vết mụn, vùng da không đều màu mà không quá dày.','Kết cấu creamy, nhiều tông màu, dễ tán.','Chấm lượng nhỏ lên vùng cần che, vỗ nhẹ bằng tay hoặc mút.',1,32);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('The Saem Cover Perfection Tip Concealer','The Saem','Che khuyết điểm',89000,10,'9dfe421af7c9119748d8_2dbb5be78ad643ea852c39241508b15a_master.jpg','Che khuyết điểm The Saem có giá tốt, phù hợp che mụn và thâm nhẹ.','Giúp vùng da đều màu hơn, dễ dùng cho makeup hằng ngày.','Kết cấu lỏng, đầu cọ tiện lợi.','Chấm lên vùng cần che, tán viền để hòa vào nền.',1,33);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('SVMY FT Color Concealer Palette','SVMY','Che khuyết điểm',139000,10,'cn-11134207-7r98o-lxwj3rmd7gatac.jfif','Bảng che khuyết điểm SVMY 3 màu hỗ trợ hiệu chỉnh nhiều vùng trên khuôn mặt.','Che quầng thâm, vùng xỉn màu, làm sáng sống mũi và vùng dưới mắt.','3 tông hiệu chỉnh: natural, lifting và salmon.','Dùng cọ nhỏ lấy màu phù hợp, tán trước hoặc sau nền tùy nhu cầu.',1,34);
INSERT INTO products(name,brand,category,price,stock,image,description,benefit,ingredients,usage_text,status,sort_order) VALUES ('Merzy Volume Curl Mascara','Merzy','Mascara',169000,10,'458386683_931178342387753_2192065793230772382_n_f8729475db074a35a004d6fa342d739a_1024x1024.jpg','Mascara Merzy giúp hàng mi rõ nét, phù hợp makeup mắt tự nhiên lẫn cá tính.','Tạo hiệu ứng mi cong, dày hơn và nổi bật hơn.','Đầu cọ dễ chải, chất mascara bám mi tốt.','Chải từ chân mi lên ngọn theo chuyển động ziczac nhẹ.',1,35);

-- V57 update product codes
UPDATE products SET product_code = CONCAT('GB-', LPAD(id, 4, '0')) WHERE product_code IS NULL OR product_code = '';

-- ===== Dữ liệu mẫu khách hàng + doanh thu tháng 1-4/2026 =====
INSERT INTO users(name,email,password,role) VALUES
('Nguyễn Thu Hà','thuhaglow@example.com','$2y$12$osim3.pR9yKQReEenQmV/.LCinnNcGLmNPxpSGpnixN7e2azPkaOu','customer'),
('Trần Minh Anh','minhanhglow@example.com','$2y$12$osim3.pR9yKQReEenQmV/.LCinnNcGLmNPxpSGpnixN7e2azPkaOu','customer'),
('Lê Phương Linh','phuonglinhglow@example.com','$2y$12$osim3.pR9yKQReEenQmV/.LCinnNcGLmNPxpSGpnixN7e2azPkaOu','customer'),
('Phạm Ngọc Mai','ngocmaiglow@example.com','$2y$12$osim3.pR9yKQReEenQmV/.LCinnNcGLmNPxpSGpnixN7e2azPkaOu','customer');

INSERT INTO orders(id,customer_name,phone,address,note,total,status,created_at) VALUES
(1,'Nguyễn Thu Hà','0912345678','Hoàn Kiếm, Hà Nội','Khách mua combo đầu năm',1848000,'Hoàn thành','2026-01-10 09:18:00'),
(2,'Trần Minh Anh','0987654321','Cầu Giấy, Hà Nội','Giao giờ hành chính',1326000,'Hoàn thành','2026-01-22 14:35:00'),
(3,'Lê Phương Linh','0901122334','Đống Đa, Hà Nội','Tư vấn thêm toner',2609000,'Hoàn thành','2026-02-06 10:12:00'),
(4,'Phạm Ngọc Mai','0933445566','Hai Bà Trưng, Hà Nội','Khách đặt online',1085000,'Hoàn thành','2026-02-20 16:40:00'),
(5,'Hoàng Bảo Ngọc','0977889900','Thanh Xuân, Hà Nội','Khách quen',2719000,'Hoàn thành','2026-03-08 11:05:00'),
(6,'Vũ Khánh Ly','0966112233','Long Biên, Hà Nội','Gói quà tặng',1697000,'Hoàn thành','2026-03-27 15:22:00'),
(7,'Đỗ Minh Châu','0944556677','Nam Từ Liêm, Hà Nội','Thanh toán khi nhận hàng',2649000,'Hoàn thành','2026-04-05 08:58:00'),
(8,'Bùi Hồng Nhung','0922334455','Hà Đông, Hà Nội','Khách chọn son + nền',1504000,'Hoàn thành','2026-04-19 19:10:00');

INSERT INTO order_items(order_id,product_id,product_name,price,quantity) VALUES
(1,7,'GlowBeauty Premium Combo 7 sản phẩm',1499000,1),(1,1,'GlowBeauty 4 Colors Eyeshadow',349000,1),
(2,3,'GlowBeauty Radiant Foundation',389000,2),(2,5,'GlowBeauty Glow Velvet Lipstick',279000,1),(2,2,'GlowBeauty Soft Rose Blush',259000,1),(2,10,'Simple Refreshing Facial Wash',125000,1),
(3,8,'GlowBeauty Luxury Makeup Banner Collection',2350000,1),(3,6,'GlowBeauty Rose Hydrating Toner',259000,1),
(4,26,'Makeup By Mario SurrealSkin Foundation',620000,1),(4,17,'Rare Beauty Soft Pinch Tinted Lip Oil',395000,1),(4,9,'Biore Sạch Dịu Nhẹ Sáng Mịn & Dưỡng Ẩm',89000,1),
(5,7,'GlowBeauty Premium Combo 7 sản phẩm',1499000,1),(5,22,'YSL Make Me Blush Bold Blurring Blush',950000,1),(5,5,'GlowBeauty Glow Velvet Lipstick',279000,1),
(6,27,'Make Up For Ever HD Skin Foundation',890000,1),(6,31,'3CE Stylenanda Waterful Foundation',420000,1),(6,3,'GlowBeauty Radiant Foundation',389000,1),
(7,8,'GlowBeauty Luxury Makeup Banner Collection',2350000,1),(7,4,'GlowBeauty Soft Veil Loose Powder',299000,1),
(8,28,'Maybelline Super Stay Lumi Matte Foundation',298000,2),(8,23,'Dasique Blending Mood Cheek Palette',315000,1),(8,18,'Merzy The Watery Dew Tint V6 Siren',179000,2),(8,21,'Romand Better Than Cheek Blush',235000,1);

-- V57 update payment data
UPDATE orders SET payment_status='Đã thanh toán' WHERE payment_status IS NULL OR payment_status='';
UPDATE orders SET payment_status='Chưa thanh toán' WHERE payment_status NOT IN ('Chưa thanh toán','Đã thanh toán');
UPDATE orders SET payment_code = CONCAT('GBPAY', DATE_FORMAT(created_at, '%y%m%d'), LPAD(id, 5, '0')) WHERE payment_code IS NULL OR payment_code='';
UPDATE order_items oi JOIN products p ON p.id=oi.product_id SET oi.product_code=p.product_code WHERE oi.product_code IS NULL OR oi.product_code='';

-- Bảng lưu khách hàng gửi form liên hệ tư vấn
CREATE TABLE IF NOT EXISTS contact_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customer_name VARCHAR(120) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  need VARCHAR(120) NOT NULL,
  message TEXT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Mới gửi',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
